/* CEAL Runtime Interface.
 *
 * Matthew A Hammer <hammer@ttic.edu>
 * 
 * This file gives the interface between the code generated by our
 * compiler and the algorithms & data-structures used by our runtime
 * system.
 *
 * Our compiler reads this header file when compiling a CEAL program
 * into conventional C code.  From the perspective of the compiler,
 * this file abstracts away the layout of various runtime structures
 * and signatures of various runtime functions.  The compiler mentions
 * these identifiers by name (but doesn't otherwise dictate or check
 * how they are defined).  The hope is that this will effectively
 * separate runtime concerns from compilation conerns (as cleanly as
 * possible, given that we are using C here).
 *
 */

/* The runtime structures used by the compiler. */
#include "runtime/trace.h"
#include "runtime/tv_signal.h"

/* Modref implementations
   -- Note that these header files also #include trace.h */
#include "runtime/modref_awar.h"
#include "runtime/modref_zwzr.h"
#include "runtime/modref_owcr.h"
#include "runtime/modref_ring.h"

/* Do performance testing. */
int cealtestperf_main(int argc, char** argv);

